use cricket_tournament;

CREATE TABLE CUSTOMER(
	CID INT PRIMARY KEY,
    CNAME VARCHAR(30),
    CITY VARCHAR(30)
);
    
CREATE TABLE ORDERS(
	ONO INT PRIMARY KEY,
    ODATE DATE,
    O_AMT INT,
	CID INT,
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
);

CREATE TABLE ITEMS(
	INO INT PRIMARY KEY,
    PRICE INT
);

CREATE TABLE ORDERS_ITEM(
	ONO INT ,
	FOREIGN KEY (ONO) REFERENCES ORDERS(ONO),
	INO INT , 
    FOREIGN KEY (INO) REFERENCES ITEMS(INO),
    QTY INT
);

CREATE TABLE WAREHOUSE(
	WARENO INT PRIMARY KEY,
    CITY VARCHAR(30)
);


CREATE TABLE SHIPMENTS(
	ONO INT,
	FOREIGN KEY (ONO) REFERENCES ORDERS(ONO),
	WARENO INT, 
    FOREIGN KEY (WARENO) REFERENCES WAREHOUSE(WARENO),
    SHIPDATE DATE     
);


INSERT INTO CUSTOMER VALUES
(1,'RINISHA','KOLKATA'),
(2,'MANISHA','ASANSOL'),
(3,'ANISHA','PATNA'),
(4,'RISHA','SILIGURI'),
(5,'LISA','KATWA'),
(6,'ISHA','KOLKATA');