use cricket_tournament;

CREATE TABLE PERSON (
D_ID INT PRIMARY KEY,
D_NAME VARCHAR(30),
D_ADDR VARCHAR(15)
);

DROP TABLE PERSON;

CREATE TABLE CAR(
REG_NO VARCHAR(10) PRIMARY KEY,
MODEL VARCHAR(10),
C_YEAR YEAR
);

CREATE TABLE ACCIDENT(
REPORT_NO INT PRIMARY KEY,
A_DATE DATE,
LOCATION VARCHAR(30)
);

DROP TABLE ACCIDENT;


CREATE TABLE OWNS(
D_ID INT,
FOREIGN KEY(D_ID) references PERSON(D_ID),
REG_NO VARCHAR(10),
foreign key(REG_NO) references CAR(REG_NO)
);

DROP TABLE OWNS;


CREATE TABLE PARTICIPATED(
D_ID INT,
foreign key(D_ID) references PERSON(D_ID),
REG_NO VARCHAR(10),
foreign key(REG_NO) references CAR(REG_NO),
REPORT_NO INT,
foreign key (REPORT_NO) references ACCIDENT(REPORT_NO),
DAMAGE_AMOUNT INT 
);

DROP TABLE PARTICIPATED;


INSERT INTO PERSON VALUES
(0,'JENSON BUTTON', 'UNIVERSITY ST'),
(1,'RUBENS BARRICHELLO', '1ST AVE'),
(2,'SEBASTIAN VETTLE', '1ST AVE'),
(3,'MARK WEBBER','1ST AVE'),
(4,'LEWIS HAMILTON','1ST AVE'),
(5,'FELIPE MASSA','UNIVERSITY ST');


INSERT INTO CAR VALUES
('SZM813','HONDA',2009),
('SZM814','TOYOTA',2009),
('SZM815','BMW',2009),



